service: serverless-notify

plugins:
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
    - .direnv/**
    - bot.session

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  memorySize: 512


functions:
  app:
    handler: app.handler
    environment:
      SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
      SENDGRID_FROM_ADDRESS: ${env:SENDGRID_FROM_ADDRESS}
      IFTTT_EVENT: ${env:IFTTT_EVENT}
      IFTTT_KEY: ${env:IFTTT_KEY}
      PUSHBULLET_ACCESS_TOKEN: ${env:PUSHBULLET_ACCESS_TOKEN}
      SERVER_CHAN_SCKEY: ${env:SERVER_CHAN_SCKEY}
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: ANY